package com.ainhize.books_api.controler;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.ainhize.books_api.model.AuthorRepository;
import com.ainhize.books_api.model.base.*;


@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
				// Hau erabilita, ez dira @ResponseBody anotazioak behar,
				// automatikoki sortuko du jsona (Jacksonekin) objetu bat bueltatzen badugu
@RequestMapping(path = "/egilea") // This means URL's start with /azterketa (after Application path)
public class EgileaController {
    @Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
    private AuthorRepository egileaRepository;

    @GetMapping(path = "/all")
    public @ResponseBody List<Egilea> getAllAuthors() {
        // This returns a JSON or XML with the users
        return egileaRepository.findAll();
    }

    @GetMapping(path = "/")
    public @ResponseBody Egilea getAuthors(@RequestParam String id) {
        // This returns a JSON or XML with the users
        return egileaRepository.findEgilea(id);
    }

    @PostMapping(path = "/add")
    public @ResponseBody Egilea saveAuthor(@RequestBody Egilea pertsona){
        return egileaRepository.save(pertsona);
    }

    @DeleteMapping (path = "/delete/{id}")
    public @ResponseBody long deleteSale(@PathVariable String id) {
        try {
            long count = egileaRepository.delete(id); // ezabatutako salmenten kopurua
            return count;

        } catch (Exception ex) {
            System.out.println("Errorea " + id + " id dun egileak ezabatzerakoan. ");
            return 0;
        }
    }
}
