package com.ainhize.books_api.controler;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import com.ainhize.books_api.model.BookRepository;
import com.ainhize.books_api.model.base.*;


@RestController // This means that this class is a Controller baina @Controller bakarrik
				// jarrita, PUT eta DELETEak ez dabiz
				// Hau erabilita, ez dira @ResponseBody anotazioak behar,
				// automatikoki sortuko du jsona (Jacksonekin) objetu bat bueltatzen badugu
@RequestMapping(path = "/liburua") // This means URL's start with /azterketa (after Application path)
public class LiburuaController {
    @Autowired // This means to get the bean called umeaRepository
				// Which is auto-generated by Spring, we will use it to handle the data
    private BookRepository liburuaRepository;

    @GetMapping(path = "/all")
    public @ResponseBody List<Liburua> getAllBooks() {
        // This returns a JSON or XML with the users
        return liburuaRepository.findAll();
    }

    @GetMapping(path = "/")
    public @ResponseBody Liburua getBook(@RequestParam String id) {
        // This returns a JSON or XML with the users
        return liburuaRepository.findLiburua(id);
    }

    @GetMapping("/byAuthor")
    public @ResponseBody List<Liburua> getBookByAuthor(@RequestParam String id) {
        return liburuaRepository.findLiburuaByAutor(id);
    }
    
    @PostMapping(path = "/add")
    public @ResponseBody Liburua saveBook(@RequestBody Liburua book){
        return liburuaRepository.save(book);
    }

    @DeleteMapping (path = "/delete/{autorID}")
    public @ResponseBody long deleteSale(@PathVariable String autorID) {
        try {
            long count = liburuaRepository.delete(autorID); // ezabatutako salmenten kopurua
            return count;

        } catch (Exception ex) {
            System.out.println("Errorea " + autorID + " autor_id dun liburuak ezabatzerakoan. ");
            return 0;
        }
    }
}
