--
-- PostgreSQL database dump
--

-- Dumped from database version 12.4
-- Dumped by pg_dump version 15.4

-- Started on 2025-10 18:31:52

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';
SET default_table_access_method = heap;

CREATE TABLE public."Elikagaia" (
    "Id" integer NOT NULL,
    "Izena" character varying(50) NOT NULL,
    "Marka" character varying(50) NOT NULL
);

ALTER TABLE public."Elikagaia" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Elikagaia_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Informazioa" (
    "Id" integer NOT NULL,
    "OsagaiaId" integer NOT NULL,
    "Urtea" integer NOT NULL,
    "Kantitatea" integer,
    "ElikagaiaId" integer NOT NULL
);

ALTER TABLE public."Informazioa" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Informazioa_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public."Osagaia" (
    "Id" integer NOT NULL,
    "Izena" character varying(50) NOT NULL,
    "Unitatea" character varying(50) NOT NULL,
    "Konparaketa" integer
);

ALTER TABLE public."Osagaia" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Osagaia_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Elikagaiak
INSERT INTO public."Elikagaia" VALUES (1, 'Moldeko ogia', 'Silueta');
INSERT INTO public."Elikagaia" VALUES (2, 'Tomatea', 'Orlando');
INSERT INTO public."Elikagaia" VALUES (3, 'Gazta', 'La Casera');
INSERT INTO public."Elikagaia" VALUES (4, 'Arrautzak', 'Natur');

-- Osagaiak
INSERT INTO public."Osagaia" VALUES (1, 'Energia', 'Kaloria', 200);
INSERT INTO public."Osagaia" VALUES (2, 'Koipea', 'gramo', 10);
INSERT INTO public."Osagaia" VALUES (3, 'Karbohidratoak', 'gramo', 30);
INSERT INTO public."Osagaia" VALUES (4, 'Azukreak', 'gramo', 9);
INSERT INTO public."Osagaia" VALUES (5, 'Proteinak', 'gramo', 26);
INSERT INTO public."Osagaia" VALUES (6, 'Gatza', 'gramo', 3);

-- Informazioa (datuak)
-- Moldeko ogia
INSERT INTO public."Informazioa" VALUES (9, 2, 2023, 11, 1);
INSERT INTO public."Informazioa" VALUES (10, 1, 2023, 100, 1);
INSERT INTO public."Informazioa" VALUES (11, 3, 2022, 60, 1);
INSERT INTO public."Informazioa" VALUES (12, 4, 2024, 12, 1);
INSERT INTO public."Informazioa" VALUES (13, 5, 2024, 20, 1);
INSERT INTO public."Informazioa" VALUES (14, 6, 2023, 1, 1);

-- Tomatea
INSERT INTO public."Informazioa" VALUES (15, 1, 2021, 90, 2);
INSERT INTO public."Informazioa" VALUES (16, 2, 2021, 5, 2);
INSERT INTO public."Informazioa" VALUES (17, 3, 2021, 50, 2);
INSERT INTO public."Informazioa" VALUES (18, 4, 2021, 15, 2);
INSERT INTO public."Informazioa" VALUES (19, 5, 2021, 10, 2);
INSERT INTO public."Informazioa" VALUES (20, 6, 2021, 6, 2);

-- Gazta (datu osagarriak, Tomatearekin antzekoak)
INSERT INTO public."Informazioa" VALUES (21, 1, 2024, 150, 3);
INSERT INTO public."Informazioa" VALUES (22, 2, 2024, 28, 3);
INSERT INTO public."Informazioa" VALUES (23, 3, 2024, 20, 3);
INSERT INTO public."Informazioa" VALUES (24, 4, 2024, 125, 3);
INSERT INTO public."Informazioa" VALUES (25, 5, 2024, 25, 3);
INSERT INTO public."Informazioa" VALUES (26, 6, 2024, 2, 3);

-- Arrautzak (datu osagarriak)
INSERT INTO public."Informazioa" VALUES (27, 1, 2024, 155, 4);
INSERT INTO public."Informazioa" VALUES (28, 2, 2024, 11, 4);
INSERT INTO public."Informazioa" VALUES (29, 3, 2024, 100, 4);
INSERT INTO public."Informazioa" VALUES (30, 4, 2024, 40, 4);
INSERT INTO public."Informazioa" VALUES (31, 5, 2024, 13, 4);
INSERT INTO public."Informazioa" VALUES (32, 6, 2024, 70, 4);

-- Sequences update
SELECT pg_catalog.setval('public."Elikagaia_Id_seq"', 4, true);
SELECT pg_catalog.setval('public."Informazioa_Id_seq"', 32, true);
SELECT pg_catalog.setval('public."Osagaia_Id_seq"', 6, true);

-- Constraints
ALTER TABLE ONLY public."Elikagaia"
    ADD CONSTRAINT "Elikagaia_pkey" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Informazioa"
    ADD CONSTRAINT "Informazioa_pkey" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Osagaia"
    ADD CONSTRAINT "Osagaia_pkey" PRIMARY KEY ("Id");

ALTER TABLE ONLY public."Informazioa"
    ADD CONSTRAINT "Informazioa_ElikagaiaId_fkey" FOREIGN KEY ("ElikagaiaId") REFERENCES public."Elikagaia"("Id") NOT VALID;

ALTER TABLE ONLY public."Informazioa"
    ADD CONSTRAINT "Informazioa_OsagaiaId_fkey" FOREIGN KEY ("OsagaiaId") REFERENCES public."Osagaia"("Id") NOT VALID;

REVOKE USAGE ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO PUBLIC;

--
-- PostgreSQL database dump complete
--
